Update workflow

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -6,4 +6,16 @@ jobs:
     name: Pull request requires changelog
     runs-on: ubuntu-latest
     steps:
-      - run: exit 1
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - name: Check that changelog updated
+        run: |
+          if ! grep --quiet CHANGELOG.md <(git diff --cached --name-only)
+          then
+            echo "ERROR - Commit failed"
+            echo "Changelog must be included with pull request."
+            exit 1
+          fi
+
