Update workflow

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -10,10 +10,14 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - run: git branch
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v35
       - name: Check that changelog updated
         run: |
-          git diff --name-only $GITHUB_SHA $(git merge-base $GITHUB_SHA $HEAD_SHA)
-        env:
-          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
-
+          if ! grep --quiet CHANGELOG.md <(${{ steps.changed-files.outputs.all_changed_files }})
+          then
+            echo "ERROR - Commit failed"
+            echo "Changelog must be included with version bump."
+            exit 1
+          fi
